### ISSUE TITLE
[FEAT] Add mariadb-client to support Kimai backup plugin

### ISSUE THREAD

**Issue by jschanz** [linuxserver/docker-kimai#5]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Please add the package **mariadb-client** to support the EasyBackupBundle for Kimai:

https://github.com/mxgross/EasyBackupBundle

mysql and mysqldump are necessary for backup the instance after installing the plugin. Without the mariadb-client-package no backup is possible

![image](https://github.com/linuxserver/docker-kimai/assets/5750462/cef6b017-51ec-4641-b6d3-b2be71bb7d19)

### Reason for change

Enable backup for the Kimai instance

### Proposed code change

`apk add mariadb-client` in Dockerfile

**Comment by nemchik** [comment]
You can use our universal package install mod https://github.com/linuxserver/docker-mods/tree/universal-package-install and you can install any apk package from https://pkgs.alpinelinux.org/ as long as the branch dropdown matches the alpine version from our Dockerfile https://github.com/linuxserver/docker-kimai/blob/main/Dockerfile (currently 3.18). We announce rebases in our changelog when the alpine version is updated.

If we see a lot of requests for this to be baked in we can add it, but for now the universal package install mod is the best option
